- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - role: geerlingguy.gitlab
      gitlab_external_url: "http://gitlab/"      
      gitlab_redirect_http_to_https: "false"
